Repository lsndr/rrule-rust, pull requests merged in 2024-05, with the labels that each got.

#107 chore: migrate to npm
  .github/workflows/build-and-test.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
  yarn.lock
Labels: enhancement

#116 fix: make all binary packages public
  npm/android-arm-eabi/package.json
  npm/android-arm64/package.json
  npm/darwin-arm64/package.json
  npm/darwin-universal/package.json
  npm/darwin-x64/package.json
  npm/freebsd-x64/package.json
  npm/linux-arm-gnueabihf/package.json
  npm/linux-arm-musleabihf/package.json
  npm/linux-arm64-gnu/package.json
  npm/linux-arm64-musl/package.json
  npm/linux-riscv64-gnu/package.json
  npm/linux-x64-gnu/package.json
  npm/linux-x64-musl/package.json
  npm/win32-arm64-msvc/package.json
  npm/win32-ia32-msvc/package.json
  npm/win32-x64-msvc/package.json
Labels: bug

#84 fix: turn `datetime.toString` into a function
  src/js/rrule_datetime.rs
  tests/datetime.spec.ts
Labels: enhancement

#133 feat: reimplement api in typescript and introduce `DateTime` class
  .eslintrc.js
  .github/workflows/build-and-test.yml
  Cargo.toml
  README.md
  benchmark/index.ts
  lib/js.rs
  lib/js/datetime.rs
  lib/js/frequency.rs
  lib/js/month.rs
  lib/js/n_weekday.rs
  lib/js/rrule.rs
  lib/js/rrule_set.rs
  lib/js/weekday.rs
  lib/lib.rs
  package-lock.json
  package.json
  src/datetime.ts
  src/index.ts
  src/js/rrule_datetime.rs
  src/js/rrule_set.rs
  src/js/rrule_timezone.rs
  src/lib/index.d.ts
  src/lib/index.js
  src/rrule-set.ts
  src/rrule.ts
  tests/daily.spec.ts
  tests/datetime.spec.ts
  tests/monthly.spec.ts
  tests/parsing.spec.ts
  tests/utils.ts
  tests/weekly.spec.ts
  tests/yearly.spec.ts
  tsconfig.build.json
  tsconfig.eslint.json
  tsconfig.json
Labels: performance

#158 feat(datetime): introduce `utc` and `local` shorthands
  src/datetime.ts
  tests/datetime.spec.ts
Labels: enhancement
